# Available commands: https://nikitabobko.github.io/AeroSpace/commands

start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
key-mapping.preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 0
inner.vertical =   0
outer.left =       0
outer.bottom =     -1
outer.top =        0
outer.right =      0

# See https://nikitabobko.github.io/AeroSpace/guide#exec-env-vars
[exec]                   # Again, you don't need to copy all config sections to your config.
inherit-env-vars = true  # If you don't touch "exec" section, it will fallback to "default-config.toml"

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented

# float QQ misc windows
[[on-window-detected]]
if.app-id = 'com.tencent.qq'
if.window-title-regex-substring = '(图片查看器|屏幕分享|(.+)的聊天记录|视频播放器)'
check-further-callbacks = true
run = 'layout floating'

# float shadowrocket
[[on-window-detected]]
if.app-id = 'com.liguangming.Shadowrocket'
check-further-callbacks = true
run = 'layout floating'

# float boop
[[on-window-detected]]
if.app-id = 'com.okatbest.boop'
check-further-callbacks = true
run = 'layout floating'

# float little arc
[[on-window-detected]]
if.window-title-regex-substring = '^Little Arc .+$'
check-further-callbacks = true
run = 'layout floating'


[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'main'

# 8 = 'secondary'
# 9 = 'secondary'

# [mode.main.binding]
#
# # All possible keys:
# # - Letters.        a, b, c, ..., z
# # - Numbers.        0, 1, 2, ..., 9
# # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# # - F-keys.         f1, f2, ..., f20
# # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
# #                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
# #                   keypadMinus, keypadMultiply, keypadPlus
# # - Arrows.         left, down, up, right
#
# # All possible modifiers: cmd, alt, ctrl, shift
#
# alt-enter = 'exec-and-forget open -n -a ghostty'
#
# # See: https://nikitabobko.github.io/AeroSpace/commands#layout
# alt-slash = 'layout tiles accordion'
#
# alt-shift-space = 'layout tiling floating'
#
# # See: https://nikitabobko.github.io/AeroSpace/commands#focus
# alt-h = 'focus left'
# alt-j = 'focus down'
# alt-k = 'focus up'
# alt-l = 'focus right'
#
# # See: https://nikitabobko.github.io/AeroSpace/commands#move
# alt-shift-h = 'move left'
# alt-shift-j = 'move down'
# alt-shift-k = 'move up'
# alt-shift-l = 'move right'
#
# # See: https://nikitabobko.github.io/AeroSpace/commands#resize
# alt-shift-minus = 'resize smart -50'
# alt-shift-equal = 'resize smart +50'
#
# # maximize and fullscreen
# alt-f = 'fullscreen'
# alt-shift-f = 'macos-native-fullscreen'
#
# # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
# alt-b = 'workspace prev --wrap-around'
# alt-n = 'workspace next --wrap-around'
# alt-1 = 'workspace 1'
# alt-2 = 'workspace 2'
# alt-3 = 'workspace 3'
# alt-4 = 'workspace 4'
# alt-5 = 'workspace 5'
# alt-6 = 'workspace 6'
# alt-7 = 'workspace 7'
# alt-8 = 'workspace 8'
# alt-9 = 'workspace 9'
#
# # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
# alt-shift-b = ['move-node-to-workspace --wrap-around prev', 'workspace --wrap-around prev']
# alt-shift-n = ['move-node-to-workspace --wrap-around next', 'workspace --wrap-around next']
# alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
# alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
# alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
# alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
# alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
# alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
# alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
# alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
# alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
#
# # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
# alt-tab = 'workspace-back-and-forth'
#
# # See: https://nikitabobko.github.io/AeroSpace/commands#mode
# alt-comma = 'mode service'
# # 'service' binding mode declaration.
# # See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# [mode.service.binding]
# esc = 'mode main'
# q = 'mode main'
# comma = ['reload-config', 'mode main']
# alt-r = ['flatten-workspace-tree', 'mode main'] # reset layout
# #s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
# alt-w = ['close-all-windows-but-current', 'mode main']
#
# h = 'focus left'
# j = 'focus down'
# k = 'focus up'
# l = 'focus right'
#
# alt-h = 'resize width -50'
# alt-j = 'resize height +50'
# alt-k = 'resize height -50'
# alt-l = 'resize width +50'
#
# alt-shift-h = 'join-with left'
# alt-shift-j = 'join-with down'
# alt-shift-k = 'join-with up'
# alt-shift-l = 'join-with right'
#
# b = 'workspace --wrap-around prev'
# n = 'workspace --wrap-around next'
# 1 = 'workspace 1'
# 2 = 'workspace 2'
# 3 = 'workspace 3'
# 4 = 'workspace 4'
# 5 = 'workspace 5'
# 6 = 'workspace 6'
# 7 = 'workspace 7'
# 8 = 'workspace 8'
# 9 = 'workspace 9'
#
# alt-b = 'move-node-to-workspace --wrap-around prev'
# alt-n = 'move-node-to-workspace --wrap-around next'
# alt-1 = 'move-node-to-workspace 1'
# alt-2 = 'move-node-to-workspace 2'
# alt-3 = 'move-node-to-workspace 3'
# alt-4 = 'move-node-to-workspace 4'
# alt-5 = 'move-node-to-workspace 5'
# alt-6 = 'move-node-to-workspace 6'
# alt-7 = 'move-node-to-workspace 7'
# alt-8 = 'move-node-to-workspace 8'
# alt-9 = 'move-node-to-workspace 9'
#
# a = 'focus-monitor --wrap-around left'
# s = 'focus-monitor --wrap-around down'
# d = 'focus-monitor --wrap-around up'
# f = 'focus-monitor --wrap-around right'
#
# alt-a = 'move-node-to-monitor --wrap-around left'
# alt-s = 'move-node-to-monitor --wrap-around down'
# alt-d = 'move-node-to-monitor --wrap-around up'
# alt-f = 'move-node-to-monitor --wrap-around right'
#
# alt-shift-a = 'move-workspace-to-monitor --wrap-around prev'
# alt-shift-f = 'move-workspace-to-monitor --wrap-around next'
#
#
